%% Exact linearization of the Simulink model iff_sim
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.7 and Simulink Control Design (TM) 5.4.
%
% Generated on: 01-Aug-2022 18:39:26

%% Specify the model name
model = 'iff_sim';

%%
lin_data;

%% Specify the analysis I/Os
% Create the analysis I/O variable IOs1
clear io
% With bottom disturbance
io(1) = linio('iff_sim/Top platform excitation/Manual Switch1',1,'input');
io(2) = linio('iff_sim/Bot platform excitation',1,'input');
io(3) = linio('iff_sim/PS-Simulink Converter6',1,'output');
io(4) = linio('iff_sim/PS-Simulink Converter7',1,'output');
io(5) = linio('iff_sim/PS-Simulink Converter8',1,'output');
io(6) = linio('iff_sim/PS-Simulink Converter2',1,'output');
io(7) = linio('iff_sim/PS-Simulink Converter1',1,'output');
io(8) = linio('iff_sim/PS-Simulink Converter',1,'output');

% Without bottom disturbance
% io(1) = linio('iff_sim/Top platform excitation/Manual Switch1',1,'input');
% io(2) = linio('iff_sim/PS-Simulink Converter6',1,'output');
% io(3) = linio('iff_sim/PS-Simulink Converter7',1,'output');
% io(4) = linio('iff_sim/PS-Simulink Converter8',1,'output');
% io(5) = linio('iff_sim/PS-Simulink Converter2',1,'output');
% io(6) = linio('iff_sim/PS-Simulink Converter1',1,'output');
% io(7) = linio('iff_sim/PS-Simulink Converter',1,'output');

%% Specify the operating point
% Use the snapshot times
op = lin_times;

%% Linearize the model
sys4D = linearize(model,io,op);

%% Get singular values
close all
figure
wlim = {2*pi*1,2*pi*1e5};
plotoptions = sigmaoptions('cstprefs'); plotoptions.FreqUnits = 'Hz';
for i = 1:length(lin_times(1:3))
    sys = sys4D(:,:,i,1);
    sigmaplot(sys,wlim,plotoptions)
    hold on
end
title('Singular values at different linearization times')
legend('\tau = \{0, 1\} s','\tau = \{0.25, 0.75\} s','\tau = 0.5 s',...
       'Location','northeast')

