%% Exact linearization of the Simulink model iff_sim
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.7 and Simulink Control Design (TM) 5.4.
%
% Generated on: 28-Jul-2022 15:19:37

%% Specify the model name
model = 'iff_sim';

%% Specify the analysis I/Os
clear io
% IO including bottom kinematic vibrations
% io(1) = linio('iff_sim/Top platform excitation/Manual Switch1',1,'input');
% io(2) = linio('iff_sim/Bot platform excitation',1,'input');
% io(3) = linio('iff_sim/IFF Controller',1,'input');
% io(4) = linio('iff_sim/PS-Simulink Converter6',1,'output');
% io(5) = linio('iff_sim/PS-Simulink Converter7',1,'output');
% io(6) = linio('iff_sim/PS-Simulink Converter8',1,'output');
% io(7) = linio('iff_sim/PS-Simulink Converter',1,'output');
% io(8) = linio('iff_sim/PS-Simulink Converter1',1,'output');
% io(9) = linio('iff_sim/PS-Simulink Converter2',1,'output');
% io(10) = linio('iff_sim/dynamic model',3,'output');
% IO excluding bottom kinematic vibrations
io(1) = linio('iff_sim/Top platform excitation/Manual Switch1',1,'input');
io(2) = linio('iff_sim/IFF Controller',1,'input');
io(3) = linio('iff_sim/PS-Simulink Converter6',1,'output');
io(4) = linio('iff_sim/PS-Simulink Converter7',1,'output');
io(5) = linio('iff_sim/PS-Simulink Converter8',1,'output');
io(6) = linio('iff_sim/PS-Simulink Converter',1,'output');
io(7) = linio('iff_sim/PS-Simulink Converter1',1,'output');
io(8) = linio('iff_sim/PS-Simulink Converter2',1,'output');
io(9) = linio('iff_sim/dynamic model',3,'output');

%% Specify the operating point
% Use the snapshot times
op = lin_times;

% Define open-loop conditions
gain_iff = 0;

linderiv = 1; % 0...simulation; 1...linearization

%% Linearize the model
% plantsys = linearize(model,io,op);
plantsys_topf = linearize(model,io,op);

